### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by maitra** [CypherpunkSamurai/frp-bypass-helper#2]
Can I use this tool to bypass a phone stuck in "An error has occurred while updating the device software." How?

**Comment by CypherpunkSamurai** [comment]
I'm not sure. This tool is like a helper to just open developer options so you can turn off `OEM Unlock`.

I think the OTA Update you're installing is corrupted. If your phone is stuck in the update try flashing only the system partition (not userdata, else you'll loose files) using pc.

**Comment by maitra** [comment]
Thanks are there instructions on how to use this tool?

**Comment by CypherpunkSamurai** [comment]
You need aide app to build it.

**Comment by CypherpunkSamurai** [comment]
Instructions have been updated, I've added release. So, Closing this issue
